# Generated by Django 2.2 on 2020-10-03 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
